config/routes.rb
Rails.application.routes.draw do

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  get 'statics/homepage'

  devise_for :users

  root "statics#homepage"

  resources :questions do 
    collection do
      get "bulk_edit", to: "questions#edit" 
      post "bulk_update", to: "questions#bulk_update"
    end
  end
  resources :users
  resources :releases
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :responses, class_name: "Question", foreign_key: "response_id"
  belongs_to :creator, class_name: "User", foreign_key: "creator_id"

  validates :content, length: { minimum: 2 }
end

app/models/questions_user.rb
class QuestionsUser < ApplicationRecord
end

app/models/release.rb
class Release < ApplicationRecord
  mount_uploader :release_art, ReleaseArtUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :user_image, UserImageUploader

  has_many :questions_created, class_name: "Question", foreign_key: "creator_id"
  has_and_belongs_to_many :questions_asked, class_name: "Question", join_table: "questions_users"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_user_logged_in_state_to_false, if: :devise_controller?, only: [:destroy]
  before_action :set_user_logged_in_state_to_true, if: :devise_controller?, only: [:create]

  helper_method :markdown
  protected

    def markdown(text)
      options = {
        filter_html:     true,
        hard_wrap:       true, 
        link_attributes: { rel: 'nofollow', target: "_blank" },
        space_after_headers: true, 
        no_images:        true

      }

      extensions = {
        autolink:           true,
        superscript:        true,
        lax_spacing:        true,
        disable_indented_code_blocks: true
      }

      renderer = Redcarpet::Render::HTML.new(options)
      markdown = Redcarpet::Markdown.new(renderer, extensions)

      markdown.render(text).html_safe
    end

    def require_admin
      unless current_user.is_admin
        redirect_to root_path, alert: "You do not have administrative access."
      end        
    end
    helper_method :require_admin

    def configure_permitted_parameters      
      devise_parameter_sanitizer.permit(:account_update, keys: [:username, :user_image])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :user_image])
      devise_parameter_sanitizer.permit(:sign_in, keys: [:logged_in])
    end

    def after_sign_in_path_for(resource)
      new_question_path
    end

    def after_sign_out_path_for(resource)
      root_path
    end

    #Doesn't work-- check later?
    def after_update_path_for(resource)
      user_path(current_user)
    end

    def set_user_logged_in_state_to_true
      session[:timestamp] = Time.now.utc
      current_user.update(logged_in: true) if current_user
    end

    def set_user_logged_in_state_to_false
      current_user.update(logged_in: false) if current_user
    end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController  

  def not_found
    render(:status => 404)
  end

  def internal_server_error
    render(:status => 500)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :update, :destroy]
  before_action :authenticate_user!

  def index
    @questions = Question.all
  end

  def show
  end

  def new
    @question = Question.new
    @display = Question.all.sample

    current_user.questions_asked << @display unless current_user.questions_asked.include?(@display)
    @questions_asked = current_user.questions_asked.where("updated_at >= ?", session[:timestamp])
    @users = User.where(logged_in: true)
    @responses = @users.map do |user|
      user.questions_created.where("created_at >= ?", session[:timestamp]).to_a
    end.reduce([]) do |prev, current|
      prev + current
    end

  end

  def edit
    @responses = current_user.questions_created
  end

  def create
    @question = Question.new(question_params)
    @question.content = @question.content.strip
    if @question.content.last != '?'
      @question.content << '?'
    end

    if @question.save
      redirect_to new_question_path
      @display = Question.all.sample

      current_user.questions_asked << @display unless current_user.questions_asked.include?(@display)
    else
      redirect_to new_question_path
    end
  end

  def bulk_update
    params['questions'].each do |id, updated_question|
      question = Question.find(id)
      question.update!(content: updated_question['content'])
    end
    redirect_to questions_url
  end

  def update
    if @question.update(question_params)
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_url, notice: 'Question was successfully destroyed.'
  end

  private
    def set_question
      @question = Question.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:content, :response_id, :creator_id).merge(creator_id: current_user.id)
    end


end

app/controllers/releases_controller.rb
class ReleasesController < ApplicationController
  before_action :set_release, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, only: [:new, :create, :edit, :update, :delete]

  def index
    @releases = Release.all
  end

  def show
  end

  def new
    @release = Release.new
  end

  def edit
  end

  def create
    @release = Release.new(release_params)

    if @release.save
      redirect_to @release, notice: 'Release was successfully created.'
    else
      render :new
    end
  end

  def update
    if @release.update(release_params)
      redirect_to @release, notice: 'Release was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @release.destroy
    redirect_to releases_url, notice: 'Release was successfully deleted.'
  end

  private
    def set_release
      @release = Release.find(params[:id])
    end

    def release_params
      params.require(:release).permit(:title, :description, :artist, :catalog_number, :release_art)
    end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def homepage
    render layout: 'homepage'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :update, :destroy]
  before_action :authenticate_user!
  before_action :require_admin, only: [:new, :create, :update, :delete]

  def index
    @users = User.all
  end

  def show
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:username, :logged_in, :is_admin, :user_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_class?(test_path)
    return 'active' if request.path.match test_path
    ''
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <title>Vaporcake</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render './layouts/partials/header' %>
    <main>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
       <%= yield %> 
    </main>
  </body>
</html>

app/views/layouts/errors.html.erb
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <title>Vaporcake</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'errors', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main class="homepage">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <div class="centered">
          <%= yield %> 
        </div>
    </main>
  </body>
</html>

app/views/layouts/homepage.html.erb
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <title>Vaporcake</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'homepage', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main class="homepage">
      <div class="shader"></div>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <div class="centered">
          <%= yield %> 
        </div>
    </main>
  </body>
</html>

app/views/layouts/partials/_header.html.erb
<header>

  <nav>
    <ul>
      <li><%= link_to 'Discography', releases_path, :class => current_class?(releases_path) %></li>
      <% if current_user %>
        <li><%= link_to 'Account', user_path(current_user), :class => current_class?(user_path(current_user)) %></li>
        <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'Log In', new_user_session_path, :class => current_class?(new_user_session_path) %></li>
        <li><%= link_to 'Register', new_user_registration_path, :class => current_class?(new_user_registration_path) %></li>
      <% end %>
    </ul>
  </nav>
  <div id="clip"><h1><%= link_to 'Vaporcake', new_question_path %></h1></div>
</header>

app/views/questions/_form.html.erb
<%= form_for(question) do |f| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :response_id, value: @display.id %>
  <% question.response_id = 0 if !question.response_id %>

  <div>
    <%= f.text_field :content, placeholder: 'Please respond with a question', :class => 'main' %>
  </div>

  <div class="actions">
    <%= f.submit 'Submit' %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<%= form_tag bulk_update_questions_path do %> 
  <% @responses.each do |question| %>
    <%= fields_for "questions[]", question do |f| %>
      <% if question.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

          <ul>
          <% question.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    <div class="form-body">
      <%= link_to 'delete', question, method: :delete, :class => 'delete', data: { confirm: 'Are you sure?' } %>
      <%= f.text_area :content, :class=> 'field' %>
      </div>
    <% end %>
  <% end %>

  <div class="actions">
    <%= submit_tag %>
  </div>
<% end %>

app/views/questions/index.html.erb
<table class="index-list">
<th colspan="2">Question Index</th>
<% @questions.each do |question| %>
    <tr>
    <td><%= link_to question.content, question %></td>       
      <td><%= link_to '[delete]', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
<% end %>
</table>
  

app/views/questions/new.html.erb
<div id="new-question-form">
<h1><%= @display.content %></h1>

<%= render 'form', question: @question %>
</div>
<div id="zalgo_txt" aria-hidden="true" >
  <% @responses.each do |question| %>
    <%= question.content %>
  <% end %>
  <% current_user.questions_asked.each do |question| %>
    <%= question.content %>
  <% end %>
</div>
<%= @responses.size %>
<% if @responses.present? %>
  <div class="glitch-this zalgo first" aria-hidden="true"></div>
  <div class="glitch-this zalgo second" aria-hidden="true"></div>
  <div class="glitch-this zalgo third" aria-hidden="true"></div>
<% end %>

app/views/questions/show.html.erb
<p>
  <%= @question.content %>
</p>

<p>
  <strong>Response:</strong>
  <%= @question.response_id %>
</p>

<p>
created by <%= User.find(@question.creator_id).username %></p>
<p>
<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>
</p>

app/views/releases/_form.html.erb
<%= form_for(release) do |f| %>
  <% if release.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(release.errors.count, "error") %> prohibited this release from being saved:</h2>

      <ul>
      <% release.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-body">
    <%= f.text_field :catalog_number, :class => 'field', :placeholder => 'Catalog Number, e.g. [vpk001]' %>

    <%= f.text_field :artist, :class => 'field', :placeholder => 'Artist Name'%>

    <%= f.text_field :title, :class => 'field', :placeholder => 'Release Title' %>

    <%= f.text_area :description, :class => 'field autosize', :placeholder => 'Description: Text can be formatted using Markdown, a lightweight markup language' %>

    <div class="file">
      <%= f.label :upload_a_cover_image %><br />
      <%= f.file_field :release_art %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit 'Submit' %>
  </div>
  
<% end %>

app/views/releases/edit.html.erb
<%= render 'form', release: @release %>

app/views/releases/index.html.erb
<ul>
  <% @releases.each do |release| %>
    <li class="grid"><%= link_to (image_tag release.release_art.bigger_thumb.url), release %></li>
  <% end %>
</ul>

app/views/releases/new.html.erb
<%= render 'form', release: @release %>

app/views/releases/show.html.erb
<div class="detail">
  <p>
    <%= image_tag(@release.release_art.detail.url, :class => 'image-detail') %>
  </p>
  <div class="text-detail">
    <h2><%= @release.artist %>: <%= @release.title %></h2>
    <h3>[<%= @release.catalog_number %>]</h3>
    <p><%= markdown(@release.description) %></p> 
    <p></p>

    <% if !!current_user && current_user.is_admin %>
      <p>
      <%= link_to 'Edit', edit_release_path(@release) %> |
      <%= link_to 'Delete', @release, method: :delete, data: { confirm: 'Are you sure?' } %>
      </p>
    <% end %>
  </div>
</div>

app/views/statics/homepage.html.erb
<h3>Welcome to the</h3> <br />
<div id="head"><h1>Vaporcake</h1></div> <br />
<h3>experience</h3>
<%= link_to 'Log In', new_user_session_path, :class => 'btn' %>
<p>New here? Please <%= link_to 'register', new_user_registration_path %>.</p>
<p><span class="itals">"Just show me the music." </span> <%= link_to 'Fine', releases_path %>.</p>

app/views/users/index.html.erb
<table class="index-list">
<th colspan="2">Users Index</th>
<% @users.each do |user| %>
    <tr>
    <td><%= link_to user.username, user %>
    <% if user.is_admin %>(admin)<% end %>
    </td>       
    <% if current_user.is_admin %><td><%= link_to '[delete]', user, method: :delete, data: { confirm: 'Are you sure?' } %></td><% end %>
    </tr>
<% end %>
</table>
  

app/views/users/show.html.erb
<div class="user">
  <div class="info">
  <% if !!@user.user_image.url %>
  <%= image_tag @user.user_image.detail.url %>
  <% end %>
  </div>
  <div class="list info">
    <% if current_user == @user %>
    <h2>Hi, <%= @user.username %></h2>
    <ul class="list">
      <li><%= link_to 'Edit Account', edit_user_registration_path %></li>
      <li><%= link_to 'Edit Responses', bulk_edit_questions_path %></li>
      <li><%= link_to 'View All Users', users_path %></li>
        <% if current_user.is_admin %>
          <li><%= link_to 'View All Questions', questions_path %></li>
          <li><%= link_to 'New Release', new_release_path %></li>
        <% end %>
    </ul>
    <% else %>
    <h2><%= @user.username %></h2>
    <% if current_user.is_admin %>

      <%= form_for(@user) do |f| %>
        <% if @user.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

            <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <p><%= f.check_box :is_admin %>Admin?<%= f.submit 'Save', :class => 'admin-toggle' %></p>
        
      <% end %>
    <% end %>

    <% end %>
  </div>
</div>
<div class="question-grid index-list">
  <ul>
    <% @user.questions_asked.each do |question| %>
      <li class="asked"><%= question.content %></li>
    <% end %>
    <% @user.questions_created.each do |question| %>
      <li><%= question.content %></li>
    <% end %>
  </ul>
</div>